-- View: adempiere.ftu_rv_order_header

-- DROP VIEW adempiere.ftu_rv_order_header;

CREATE OR REPLACE VIEW adempiere.ftu_rv_order_header
 AS
 SELECT o.ad_client_id,
    o.ad_org_id,
    o.isactive,
    o.created,
    o.createdby,
    o.updated,
    o.updatedby,
    o.c_order_id,
    o.issotrx,
    o.documentno,
    o.docstatus,
    o.c_doctype_id,
    o.c_bpartner_id,
    bp.value AS bpvalue,
    bp.taxid AS bptaxid,
    bp.naics,
    bp.duns,
    oi.c_location_id AS org_location_id,
    oi.taxid,
    o.m_warehouse_id,
    wh.c_location_id AS warehouse_location_id,
    dt.printname AS documenttype,
    dt.documentnote AS documenttypenote,
    dt.isconsignmentdocument,
    o.salesrep_id,
    COALESCE(ubp.name, u.name) AS salesrep_name,
    o.dateordered,
    o.datepromised,
    bpg.greeting AS bpgreeting,
    bp.name,
    bp.name2,
    bpcg.greeting AS bpcontactgreeting,
    bpc.title,
    bpc.phone,
    NULLIF(bpc.name::text, bp.name::text) AS contactname,
    bpl.c_location_id,
    l.postal::text || l.postal_add::text AS postal,
    bp.referenceno,
    o.bill_bpartner_id,
    o.bill_location_id,
    o.bill_user_id,
    bbp.value AS bill_bpvalue,
    bbp.taxid AS bill_bptaxid,
    bbp.name AS bill_name,
    bbp.name2 AS bill_name2,
    bbpc.title AS bill_title,
    bbpc.phone AS bill_phone,
    NULLIF(bbpc.name::text, bbp.name::text) AS bill_contactname,
    bbpl.c_location_id AS bill_c_location_id,
    o.description,
    o.poreference,
    o.c_currency_id,
    pt.name AS paymentterm,
    pt.documentnote AS paymenttermnote,
    o.c_charge_id,
    o.chargeamt,
    o.totallines,
    o.grandtotal,
    o.grandtotal AS amtinwords,
    o.m_pricelist_id,
    o.istaxincluded,
    o.volume,
    o.weight,
    o.c_campaign_id,
    o.c_project_id,
    o.c_activity_id,
    o.m_shipper_id,
    o.deliveryrule,
    o.deliveryviarule,
    o.priorityrule,
    o.invoicerule,
    COALESCE(oi.logo_id, ci.logo_id) AS logo_id,
    o.ad_orgtrx_id,
    o.ad_user_id,
    o.amountrefunded,
    o.amounttendered,
    o.c_bpartner_location_id,
    o.c_cashline_id,
    o.c_cashplanline_id,
    o.c_conversiontype_id,
    o.c_doctypetarget_id,
    o.copyfrom,
    o.c_payment_id,
    o.c_paymentterm_id,
    o.c_pos_id,
    o.dateacct,
    o.dateprinted,
    o.docaction,
    o.dropship_bpartner_id,
    o.dropship_location_id,
    o.dropship_user_id,
    o.freightamt,
    o.freightcostrule,
    o.isapproved,
    o.iscreditapproved,
    o.isdelivered,
    o.isdiscountprinted,
    o.isdropship,
    o.isinvoiced,
    o.ispayschedulevalid,
    o.isprinted,
    o.isselected,
    o.isselfservice,
    o.istransferred,
    o.link_order_id,
    o.m_freightcategory_id,
    o.ordertype,
    o.pay_bpartner_id,
    o.pay_location_id,
    o.paymentrule,
    o.posted,
    o.processed,
    o.processedon,
    o.promotioncode,
    o.ref_order_id,
    o.sendemail,
    o.user1_id,
    o.user2_id,
    wh.ad_org_id AS m_warehouse_ad_org_id,
    wh.description AS m_warehouse_description,
    wh.isactive AS m_warehouse_isactive,
    wh.isdisallownegativeinv,
    wh.isintransit,
    wh.m_warehousesource_id,
    wh.name AS m_warehouse_name,
    wh.replenishmentclass,
    wh.separator,
    wh.value AS m_warehouse_value,
    wh.isconsignmentwarehouse,
    pt.ad_org_id AS c_paymentterm_ad_org_id,
    pt.afterdelivery,
    pt.description AS c_paymentterm_description,
    pt.discount,
    pt.discount2,
    pt.discountdays,
    pt.discountdays2,
    pt.fixmonthcutoff,
    pt.fixmonthday,
    pt.fixmonthoffset,
    pt.gracedays,
    pt.isactive AS c_paymentterm_isactive,
    pt.isdefault,
    pt.isduefixed,
    pt.isnextbusinessday,
    pt.isvalid,
    pt.netday,
    pt.netdays,
    pt.paymenttermusage,
    pt.value AS m_paymentterm_value,
    bp.acqusitioncost AS bp_acqusitioncost,
    bp.actuallifetimevalue AS bp_actuallifetimevalue,
    bp.ad_language AS bp_ad_language,
    bp.ad_orgbp_id AS bp_ad_orgbp_id,
    bp.ad_org_id AS bp_ad_org_id,
    bp.bpartner_parent_id AS bp_bpartner_parent_id,
    bp.c_bp_group_id AS bp_c_bp_group_id,
    bp.c_dunning_id AS bp_c_dunning_id,
    bp.c_greeting_id AS bp_c_greeting_id,
    bp.c_invoiceschedule_id AS bp_c_invoiceschedule_id,
    bp.c_paymentterm_id AS bp_c_paymentterm_id,
    bp.created AS bp_created,
    bp.createdby AS bp_createdby,
    bp.c_taxgroup_id AS bp_c_taxgroup_id,
    bp.deliveryrule AS bp_deliveryrule,
    bp.deliveryviarule AS bp_deliveryviarule,
    bp.description AS bp_description,
    bp.dunninggrace AS bp_dunninggrace,
    bp.firstsale AS bp_firstsale,
    bp.flatdiscount AS bp_flatdiscount,
    bp.freightcostrule AS bp_freightcostrule,
    bp.invoicerule AS bp_invoicerule,
    bp.isactive AS bp_isactive,
    bp.iscustomer AS bp_iscustomer,
    bp.isdiscountprinted AS bp_isdiscountprinted,
    bp.isemployee AS bp_isemployee,
    bp.ismanufacturer AS bp_ismanufacturer,
    bp.isonetime AS bp_isonetime,
    bp.ispotaxexempt AS bp_ispotaxexempt,
    bp.isprospect AS bp_isprospect,
    bp.issalesrep AS bp_issalesrep,
    bp.issummary AS bp_issummary,
    bp.istaxexempt AS bp_istaxexempt,
    bp.isvendor AS bp_isvendor,
    bp.isconsignmentpartner,
    bp.logo_id AS bp_logo_id,
    bp.m_discountschema_id AS bp_m_discountschema_id,
    bp.m_pricelist_id AS bp_m_pricelist_id,
    bp.numberemployees AS bp_numberemployees,
    bp.paymentrule AS bp_paymentrule,
    bp.paymentrulepo AS bp_paymentrulepo,
    bp.po_discountschema_id AS bp_po_discountschema_id,
    bp.po_paymentterm_id AS bp_po_paymentterm_id,
    bp.po_pricelist_id AS bp_po_pricelist_id,
    bp.poreference AS bp_poreference,
    bp.potentiallifetimevalue AS bp_potentiallifetimevalue,
    bp.rating AS bp_rating,
    bp.salesrep_id AS bp_salesrep_id,
    bp.salesvolume AS bp_salesvolume,
    bp.sendemail AS bp_sendemail,
    bp.shareofcustomer AS bp_shareofcustomer,
    bp.shelflifeminpct AS bp_shelflifeminpct,
    bp.so_creditlimit AS bp_so_creditlimit,
    bp.socreditstatus AS bp_socreditstatus,
    bp.so_creditused AS bp_so_creditused,
    bp.so_description AS bp_so_description,
    bp.totalopenbalance AS bp_totalopenbalance,
    bp.updated AS bp_updated,
    bp.updatedby AS bp_updatedby,
    bp.url AS bp_url,
    bp.m_warehouse_id AS m_warehousetarget_id,
    bpg.ad_org_id AS c_greeting_ad_org_id,
    bpg.isactive AS c_greeting_isactive,
    bpg.isfirstnameonly,
    bpg.name AS c_greeting_name,
    bpl.ad_org_id AS bp_location_ad_org_id,
    bpl.c_bpartner_id AS bp_location_c_bpartner_id,
    bpl.created AS bp_location_created,
    bpl.createdby AS bp_location_createdby,
    bpl.c_salesregion_id AS bp_location_c_salesregion_id,
    bpl.fax AS bp_location_fax,
    bpl.isactive AS bp_location_isactive,
    bpl.isbillto AS bp_location_isbillto,
    bpl.isdn AS bp_location_isdn,
    bpl.ispayfrom AS bp_location_ispayfrom,
    bpl.isremitto AS bp_location_isremitto,
    bpl.isshipto AS bp_location_isshipto,
    bpl.name AS bp_location_name,
    bpl.phone AS bp_location_phone,
    bpl.phone2 AS bp_location_phone2,
    bpl.updated AS bp_location_updated,
    bpl.updatedby AS bp_location_updatedby,
    l.address1,
    l.address2,
    l.address3,
    l.address4,
    l.ad_org_id AS c_location_ad_org_id,
    l.c_city_id,
    l.c_country_id,
    l.city,
    l.created AS c_location_created,
    l.createdby AS c_location_createdby,
    l.c_region_id,
    l.isactive AS c_location_isactive,
    l.regionname,
    l.updated AS c_location_updated,
    l.updatedby AS c_location_updatedby,
    bpc.ad_org_id AS ad_user_ad_org_id,
    bpc.ad_orgtrx_id AS ad_user_ad_orgtrx_id,
    bpc.birthday AS ad_user_ad_birthday,
    bpc.c_bpartner_id AS ad_user_c_bpartner_id,
    bpc.c_bpartner_location_id AS ad_user_c_bpartner_location_id,
    bpc.c_greeting_id AS ad_user_c_greeting_id,
    bpc.comments AS ad_user_comments,
    bpc.created AS ad_user_created,
    bpc.createdby AS ad_user_createdby,
    bpc.description AS ad_user_description,
    bpc.email AS ad_user_email,
    bpc.fax AS ad_user_fax,
    bpc.isactive AS ad_user_isactive,
    bpc.lastcontact AS ad_user_lastcontact,
    bpc.lastresult AS ad_user_lastresult,
    bpc.phone2 AS ad_user_phone2,
    bpc.supervisor_id AS ad_user_supervisor_id,
    bpc.updated AS ad_user_updated,
    bpc.updatedby AS ad_user_updatedby,
    bpc.value AS ad_user_value,
    bpcg.ad_org_id AS c_user_greeting_ad_org_id,
    bpcg.isactive AS c_user_greeting_isactive,
    bpcg.isfirstnameonly AS c_user_greeting_isfnameonly,
    bpcg.name AS c_user_greeting_name,
    oi.ad_org_id AS ad_orginfo_ad_org_id,
    oi.ad_orgtype_id,
    oi.c_calendar_id,
    oi.created AS ad_orginfo_created,
    oi.createdby AS ad_orginfo_createdby,
    oi.dropship_warehouse_id,
    oi.duns AS ad_orginfo_duns,
    oi.email AS ad_orginfo_email,
    oi.fax AS ad_orginfo_fax,
    oi.isactive AS ad_orginfo_isactive,
    oi.m_warehouse_id AS ad_orginfo_m_warehouse_id,
    oi.parent_org_id,
    oi.phone AS ad_orginfo_phone,
    oi.phone2 AS ad_orginfo_phone2,
    oi.receiptfootermsg,
    oi.supervisor_id,
    oi.updated AS ad_orginfo_updated,
    oi.updatedby AS ad_orginfo_updatedby,
    u.ad_org_id AS salesrep_ad_org_id,
    u.ad_orgtrx_id AS salesrep_ad_orgtrx_id,
    u.birthday AS salesrep_ad_birthday,
    u.c_bpartner_id AS salesrep_c_bpartner_id,
    u.c_bpartner_location_id AS salesrep_c_bp_location_id,
    u.c_greeting_id AS salesrep_c_greeting_id,
    u.comments AS salesrep_comments,
    u.created AS salesrep_created,
    u.createdby AS salesrep_createdby,
    u.description AS salesrep_description,
    u.email AS salesrep_email,
    u.fax AS salesrep_fax,
    u.isactive AS salesrep_isactive,
    u.lastcontact AS salesrep_lastcontact,
    u.lastresult AS salesrep_lastresult,
    u.phone AS salesrep_phone,
    u.phone2 AS salesrep_phone2,
    u.supervisor_id AS salesrep_supervisor_id,
    u.title AS salesrep_title,
    u.updated AS salesrep_updated,
    u.updatedby AS salesrep_updatedby,
    u.value AS salesrep_value,
    ubp.acqusitioncost AS salesrep_bp_acqusitioncost,
    ubp.actuallifetimevalue AS salesrep_bp_actuallifetimeval,
    ubp.ad_language AS salesrep_bp_ad_language,
    ubp.ad_orgbp_id AS salesrep_bp_ad_orgbp_id,
    ubp.ad_org_id AS salesrep_bp_ad_org_id,
    ubp.bpartner_parent_id AS salesrep_bp_bpartner_parent_id,
    ubp.c_bp_group_id AS salesrep_bp_c_bp_group_id,
    ubp.c_dunning_id AS salesrep_bp_c_dunning_id,
    ubp.c_greeting_id AS salesrep_bp_c_greeting_id,
    ubp.c_invoiceschedule_id AS salesrep_bp_c_invoicesched_id,
    ubp.c_paymentterm_id AS salesrep_bp_c_paymentterm_id,
    ubp.created AS salesrep_bp_created,
    ubp.createdby AS salesrep_bp_createdby,
    ubp.c_taxgroup_id AS salesrep_bp_c_taxgroup_id,
    ubp.deliveryrule AS salesrep_bp_deliveryrule,
    ubp.deliveryviarule AS salesrep_bp_deliveryviarule,
    ubp.description AS salesrep_bp_description,
    ubp.dunninggrace AS salesrep_bp_dunninggrace,
    ubp.duns AS salesrep_bp_duns,
    ubp.firstsale AS salesrep_bp_firstsale,
    ubp.flatdiscount AS salesrep_bp_flatdiscount,
    ubp.freightcostrule AS salesrep_bp_freightcostrule,
    ubp.invoicerule AS salesrep_bp_invoicerule,
    ubp.isactive AS salesrep_bp_isactive,
    ubp.iscustomer AS salesrep_bp_iscustomer,
    ubp.isdiscountprinted AS salesrep_bp_isdiscountprinted,
    ubp.isemployee AS salesrep_bp_isemployee,
    ubp.ismanufacturer AS salesrep_bp_ismanufacturer,
    ubp.isonetime AS salesrep_bp_isonetime,
    ubp.ispotaxexempt AS salesrep_bp_ispotaxexempt,
    ubp.isprospect AS salesrep_bp_isprospect,
    ubp.issalesrep AS salesrep_bp_issalesrep,
    ubp.issummary AS salesrep_bp_issummary,
    ubp.istaxexempt AS salesrep_bp_istaxexempt,
    ubp.isvendor AS salesrep_bp_isvendor,
    ubp.logo_id AS salesrep_bp_logo_id,
    ubp.m_discountschema_id AS salesrep_bp_m_discountschm_id,
    ubp.m_pricelist_id AS salesrep_bp_m_pricelist_id,
    ubp.naics AS salesrep_bp_naics,
    ubp.name2 AS salesrep_bp_name2,
    ubp.numberemployees AS salesrep_bp_numberemployees,
    ubp.paymentrule AS salesrep_bp_paymentrule,
    ubp.paymentrulepo AS salesrep_bp_paymentrulepo,
    ubp.po_discountschema_id AS salesrep_bp_po_discountschm_id,
    ubp.po_paymentterm_id AS salesrep_bp_po_paymentterm_id,
    ubp.po_pricelist_id AS salesrep_bp_po_pricelist_id,
    ubp.poreference AS salesrep_bp_poreference,
    ubp.potentiallifetimevalue AS salesrep_bp_potentiallifetime,
    ubp.rating AS salesrep_bp_rating,
    ubp.referenceno AS salesrep_bp_referenceno,
    ubp.salesrep_id AS salesrep_bp_salesrep_id,
    ubp.salesvolume AS salesrep_bp_salesvolume,
    ubp.sendemail AS salesrep_bp_sendemail,
    ubp.shareofcustomer AS salesrep_bp_shareofcustomer,
    ubp.shelflifeminpct AS salesrep_bp_shelflifeminpct,
    ubp.so_creditlimit AS salesrep_bp_so_creditlimit,
    ubp.socreditstatus AS salesrep_bp_socreditstatus,
    ubp.so_creditused AS salesrep_bp_so_creditused,
    ubp.so_description AS salesrep_bp_so_description,
    ubp.taxid AS salesrep_bp_taxid,
    ubp.totalopenbalance AS salesrep_bp_totalopenbalance,
    ubp.updated AS salesrep_bp_updated,
    ubp.updatedby AS salesrep_bp_updatedby,
    ubp.url AS salesrep_bp_url,
    ubp.value AS salesrep_bp_value,
    bbp.acqusitioncost AS bill_bp_acqusitioncost,
    bbp.actuallifetimevalue AS bill_bp_actuallifetimevalue,
    bbp.ad_language AS bill_bp_ad_language,
    bbp.ad_orgbp_id AS bill_bp_ad_orgbp_id,
    bbp.ad_org_id AS bill_bp_ad_org_id,
    bbp.bpartner_parent_id AS bill_bp_bpartner_parent_id,
    bbp.c_bp_group_id AS bill_bp_c_bp_group_id,
    bbp.c_dunning_id AS bill_bp_c_dunning_id,
    bbp.c_greeting_id AS bill_bp_c_greeting_id,
    bbp.c_invoiceschedule_id AS bill_bp_c_invoiceschedule_id,
    bbp.c_paymentterm_id AS bill_bp_c_paymentterm_id,
    bbp.created AS bill_bp_created,
    bbp.createdby AS bill_bp_createdby,
    bbp.c_taxgroup_id AS bill_bp_c_taxgroup_id,
    bbp.deliveryrule AS bill_bp_deliveryrule,
    bbp.deliveryviarule AS bill_bp_deliveryviarule,
    bbp.description AS bill_bp_description,
    bbp.dunninggrace AS bill_bp_dunninggrace,
    bbp.duns AS bill_bp_duns,
    bbp.firstsale AS bill_bp_firstsale,
    bbp.flatdiscount AS bill_bp_flatdiscount,
    bbp.freightcostrule AS bill_bp_freightcostrule,
    bbp.invoicerule AS bill_bp_invoicerule,
    bbp.isactive AS bill_bp_isactive,
    bbp.iscustomer AS bill_bp_iscustomer,
    bbp.isdiscountprinted AS bill_bp_isdiscountprinted,
    bbp.isemployee AS bill_bp_isemployee,
    bbp.ismanufacturer AS bill_bp_ismanufacturer,
    bbp.isonetime AS bill_bp_isonetime,
    bbp.ispotaxexempt AS bill_bp_ispotaxexempt,
    bbp.isprospect AS bill_bp_isprospect,
    bbp.issalesrep AS bill_bp_issalesrep,
    bbp.issummary AS bill_bp_issummary,
    bbp.istaxexempt AS bill_bp_istaxexempt,
    bbp.isvendor AS bill_bp_isvendor,
    bbp.logo_id AS bill_bp_logo_id,
    bbp.m_discountschema_id AS bill_bp_m_discountschema_id,
    bbp.m_pricelist_id AS bill_bp_m_pricelist_id,
    bbp.naics AS bill_bp_naics,
    bbp.numberemployees AS bill_bp_numberemployees,
    bbp.paymentrule AS bill_bp_paymentrule,
    bbp.paymentrulepo AS bill_bp_paymentrulepo,
    bbp.po_discountschema_id AS bill_bp_po_discountschema_id,
    bbp.po_paymentterm_id AS bill_bp_po_paymentterm_id,
    bbp.po_pricelist_id AS bill_bp_po_pricelist_id,
    bbp.poreference AS bill_bp_poreference,
    bbp.potentiallifetimevalue AS bill_bp_potentiallifetimevalue,
    bbp.rating AS bill_bp_rating,
    bbp.referenceno AS bill_bp_referenceno,
    bbp.salesrep_id AS bill_bp_salesrep_id,
    bbp.salesvolume AS bill_bp_salesvolume,
    bbp.sendemail AS bill_bp_sendemail,
    bbp.shareofcustomer AS bill_bp_shareofcustomer,
    bbp.shelflifeminpct AS bill_bp_shelflifeminpct,
    bbp.so_creditlimit AS bill_bp_so_creditlimit,
    bbp.socreditstatus AS bill_bp_socreditstatus,
    bbp.so_creditused AS bill_bp_so_creditused,
    bbp.so_description AS bill_bp_so_description,
    bbp.totalopenbalance AS bill_bp_totalopenbalance,
    bbp.updated AS bill_bp_updated,
    bbp.updatedby AS bill_bp_updatedby,
    bbp.url AS bill_bp_url,
    bbpl.ad_org_id AS bill_bp_location_ad_org_id,
    bbpl.c_bpartner_id AS bill_bp_location_c_bpartner_id,
    bbpl.created AS bill_bp_location_created,
    bbpl.createdby AS bill_bp_location_createdby,
    bbpl.c_salesregion_id AS bill_bp_location_c_salesreg_id,
    bbpl.fax AS bill_bp_location_fax,
    bbpl.isactive AS bill_bp_location_isactive,
    bbpl.isbillto AS bill_bp_location_isbillto,
    bbpl.isdn AS bill_bp_location_isdn,
    bbpl.ispayfrom AS bill_bp_location_ispayfrom,
    bbpl.isremitto AS bill_bp_location_isremitto,
    bbpl.isshipto AS bill_bp_location_isshipto,
    bbpl.name AS bill_bp_location_name,
    bbpl.phone AS bill_bp_location_phone,
    bbpl.phone2 AS bill_bp_location_phone2,
    bbpl.updated AS bill_bp_location_updated,
    bbpl.updatedby AS bill_bp_location_updatedby,
    bbpc.ad_org_id AS bill_user_ad_org_id,
    bbpc.ad_orgtrx_id AS bill_user_ad_orgtrx_id,
    bbpc.birthday AS bill_user_ad_birthday,
    bbpc.c_bpartner_id AS bill_user_c_bpartner_id,
    bbpc.c_bpartner_location_id AS bill_user_c_bp_location_id,
    bbpc.c_greeting_id AS bill_user_c_greeting_id,
    bbpc.comments AS bill_user_comments,
    bbpc.created AS bill_user_created,
    bbpc.createdby AS bill_user_createdby,
    bbpc.description AS bill_user_description,
    bbpc.email AS bill_user_email,
    bbpc.fax AS bill_user_fax,
    bbpc.isactive AS bill_user_isactive,
    bbpc.lastcontact AS bill_user_lastcontact,
    bbpc.lastresult AS bill_user_lastresult,
    bbpc.phone2 AS bill_user_phone2,
    bbpc.supervisor_id AS bill_user_supervisor_id,
    bbpc.updated AS bill_user_updated,
    bbpc.updatedby AS bill_user_updatedby,
    bbpc.value AS bill_user_value,
    cur.cursymbol,
    cur.description AS cur_description,
    o.c_order_id AS ftu_rv_order_header_id
   FROM c_order o
     JOIN c_doctype dt ON o.c_doctype_id = dt.c_doctype_id
     JOIN m_warehouse wh ON o.m_warehouse_id = wh.m_warehouse_id
     JOIN c_paymentterm pt ON o.c_paymentterm_id = pt.c_paymentterm_id
     JOIN c_bpartner bp ON o.c_bpartner_id = bp.c_bpartner_id
     LEFT JOIN c_greeting bpg ON bp.c_greeting_id = bpg.c_greeting_id
     JOIN c_bpartner_location bpl ON o.c_bpartner_location_id = bpl.c_bpartner_location_id
     JOIN c_location l ON bpl.c_location_id = l.c_location_id
     LEFT JOIN ad_user bpc ON o.ad_user_id = bpc.ad_user_id
     LEFT JOIN c_greeting bpcg ON bpc.c_greeting_id = bpcg.c_greeting_id
     JOIN ad_orginfo oi ON o.ad_org_id = oi.ad_org_id
     JOIN ad_clientinfo ci ON o.ad_client_id = ci.ad_client_id
     LEFT JOIN ad_user u ON o.salesrep_id = u.ad_user_id
     LEFT JOIN c_bpartner ubp ON u.c_bpartner_id = ubp.c_bpartner_id
     JOIN c_bpartner bbp ON o.bill_bpartner_id = bbp.c_bpartner_id
     JOIN c_bpartner_location bbpl ON o.bill_location_id = bbpl.c_bpartner_location_id
     LEFT JOIN ad_user bbpc ON o.bill_user_id = bbpc.ad_user_id
     LEFT JOIN c_currency cur ON o.c_currency_id = cur.c_currency_id;

ALTER TABLE adempiere.ftu_rv_order_header
    OWNER TO adempiere;

-- View: adempiere.ftu_rv_order_line

-- DROP VIEW adempiere.ftu_rv_order_line;

CREATE OR REPLACE VIEW adempiere.ftu_rv_order_line
 AS
 SELECT o.ad_client_id,
    o.ad_org_id,
    o.created,
    o.createdby,
    o.updated,
    o.updatedby,
    o.isactive,
    ol.c_order_id,
    ol.m_product_id,
    ol.qtyinvoiced,
    ol.qtyentered,
    ol.qtydelivered,
    ol.qtyordered
   FROM c_order o
     JOIN ( SELECT c_orderline.c_order_id,
            c_orderline.m_product_id,
            sum(c_orderline.qtyinvoiced) AS qtyinvoiced,
            sum(c_orderline.qtyentered) AS qtyentered,
            sum(c_orderline.qtydelivered) AS qtydelivered,
            sum(c_orderline.qtyordered) AS qtyordered
           FROM c_orderline
          GROUP BY c_orderline.c_order_id, c_orderline.m_product_id) ol ON o.c_order_id = ol.c_order_id;

ALTER TABLE adempiere.ftu_rv_order_line
    OWNER TO adempiere;


-- View: adempiere.ftu_rv_movement_header

-- DROP VIEW adempiere.ftu_rv_movement_header;

CREATE OR REPLACE VIEW adempiere.ftu_rv_movement_header
 AS
 SELECT m.posted,
    m.poreference,
    m.dd_order_id,
    m.isapproved,
    m.isintransit,
    m.datereceived,
    m.approvalamt,
    m.salesrep_id,
    m.docstatus,
    m.priorityrule,
    m.chargeamt,
    m.deliveryrule,
    m.deliveryviarule,
    m.m_movement_id,
    m.c_doctype_id,
    m.movementdate,
    m.description,
    m.documentno,
    m.freightcostrule,
    m.freightamt,
    m.processedon,
    m.isactive,
    m.ad_org_id,
    m.ad_orgtrx_id,
    m.ad_user_id,
    m.c_activity_id,
    m.c_bpartner_id,
    m.c_bpartner_location_id,
    m.c_campaign_id,
    m.c_charge_id,
    m.user2_id,
    m.c_project_id,
    m.m_shipper_id,
    m.reversal_id,
    m.user1_id,
    m.created,
    m.updated,
    m.ad_client_id,
    m.updatedby,
    m.createdby,
    m.docaction,
    m.m_movement_id AS ftu_rv_movement_header_id
   FROM m_movement m;

ALTER TABLE adempiere.ftu_rv_movement_header
    OWNER TO adempiere;

-- View: adempiere.ftu_rv_movement_line

-- DROP VIEW adempiere.ftu_rv_movement_line;

CREATE OR REPLACE VIEW adempiere.ftu_rv_movement_line
 AS
 SELECT ml.targetqty,
    ml.scrappedqty,
    ml.confirmedqty,
    ml.processed,
    ml.line,
    ml.movementqty,
    ml.m_attributesetinstanceto_id,
    ml.m_locatorto_id,
    ml.m_locator_id,
    ml.m_product_id,
    ml.m_attributesetinstance_id,
    ml.dd_orderline_id,
    ml.description,
    ml.m_movementline_id,
    ml.updated,
    ml.isactive,
    ( SELECT p.value
           FROM m_product p
          WHERE p.m_product_id = ml.m_product_id) AS value,
    ml.m_movement_id,
    ml.reversalline_id,
    ml.created,
    ml.ad_org_id,
    ml.updatedby,
    ml.createdby,
    ml.ad_client_id
   FROM m_movementline ml
     JOIN m_movement m ON m.m_movement_id = ml.m_movement_id;

ALTER TABLE adempiere.ftu_rv_movement_line
    OWNER TO adempiere;

-- View: adempiere.ftu_rv_inout_header

-- DROP VIEW adempiere.ftu_rv_inout_header;

CREATE OR REPLACE VIEW adempiere.ftu_rv_inout_header
 AS
 SELECT io.ad_client_id,
    io.ad_org_id,
    io.isactive,
    io.created,
    io.createdby,
    io.updated,
    io.updatedby,
    io.m_inout_id,
    io.issotrx,
    io.documentno,
    io.docstatus,
    io.c_doctype_id,
    io.c_bpartner_id,
    bp.value AS bpvalue,
    bp.taxid AS bptaxid,
    bp.naics,
    bp.duns,
    oi.c_location_id AS org_location_id,
    oi.taxid,
    io.m_warehouse_id,
    wh.c_location_id AS warehouse_location_id,
    dt.printname AS documenttype,
    dt.documentnote AS documenttypenote,
    dt.isconsignmentdocument,
    io.c_order_id,
    io.movementdate,
    io.movementtype,
    bpg.greeting AS bpgreeting,
    bp.name,
    bp.name2,
    bpcg.greeting AS bpcontactgreeting,
    bpc.title,
    bpc.phone,
    NULLIF(bpc.name::text, bp.name::text) AS contactname,
    bpl.c_location_id,
    l.postal::text || l.postal_add::text AS postal,
    bp.referenceno,
    io.description,
    io.poreference,
    io.dateordered,
    io.volume,
    io.weight,
    io.m_shipper_id,
    io.deliveryrule,
    io.deliveryviarule,
    io.priorityrule,
    COALESCE(oi.logo_id, ci.logo_id) AS logo_id,
    io.ad_orgtrx_id,
    io.ad_user_id,
    io.c_activity_id,
    io.c_bpartner_location_id,
    io.c_campaign_id,
    io.c_charge_id,
    io.chargeamt,
    io.c_invoice_id,
    io.c_project_id,
    io.createconfirm,
    io.createfrom,
    io.createpackage,
    io.dateacct,
    io.dateprinted,
    io.datereceived,
    io.docaction,
    io.dropship_bpartner_id,
    io.dropship_location_id,
    io.dropship_user_id,
    io.freightamt,
    io.freightcostrule,
    io.generateto,
    io.isapproved,
    io.isdropship,
    io.isindispute,
    io.isintransit AS m_inout_isintransit,
    io.isprinted,
    io.m_rma_id,
    io.nopackages,
    io.pickdate,
    io.posted,
    io.processed,
    io.processedon,
    io.processing,
    io.ref_inout_id,
    io.reversal_id,
    io.salesrep_id AS m_inout_salesrep_id,
    io.sendemail,
    io.shipdate,
    io.trackingno,
    io.user1_id,
    io.user2_id,
    bp.acqusitioncost AS c_bp_acqusitioncost,
    bp.actuallifetimevalue AS c_bp_actuallifetimevalue,
    bp.ad_language AS c_bp_ad_language,
    bp.ad_orgbp_id AS c_bp_ad_orgbp_id,
    bp.ad_org_id AS c_bp_ad_org_id,
    bp.bpartner_parent_id AS c_bp_bpartner_parent_id,
    bp.c_bp_group_id AS c_bp_c_bp_group_id,
    bp.c_dunning_id AS c_bp_c_dunning_id,
    bp.c_greeting_id AS c_bp_c_greeting_id,
    bp.c_invoiceschedule_id AS c_bp_c_invoiceschedule_id,
    bp.c_paymentterm_id AS c_bp_c_paymentterm_id,
    bp.created AS c_bp_created,
    bp.createdby AS c_bp_createdby,
    bp.c_taxgroup_id AS c_bp_c_taxgroup_id,
    bp.deliveryrule AS c_bp_deliveryrule,
    bp.deliveryviarule AS c_bp_deliveryviarule,
    bp.description AS c_bp_description,
    bp.dunninggrace AS c_bp_dunninggrace,
    bp.firstsale AS c_bp_firstsale,
    bp.flatdiscount AS c_bp_flatdiscount,
    bp.freightcostrule AS c_bp_freightcostrule,
    bp.invoicerule AS c_bp_invoicerule,
    bp.isactive AS c_bp_isactive,
    bp.iscustomer AS c_bp_iscustomer,
    bp.isdiscountprinted AS c_bp_isdiscountprinted,
    bp.isemployee AS c_bp_isemployee,
    bp.ismanufacturer AS c_bp_ismanufacturer,
    bp.isonetime AS c_bp_isonetime,
    bp.ispotaxexempt AS c_bp_ispotaxexempt,
    bp.isprospect AS c_bp_isprospect,
    bp.issalesrep AS c_bp_issalesrep,
    bp.issummary AS c_bp_issummary,
    bp.istaxexempt AS c_bp_istaxexempt,
    bp.isvendor AS c_bp_isvendor,
    bp.logo_id AS c_bp_logo_id,
    bp.m_discountschema_id AS c_bp_m_discountschema_id,
    bp.m_pricelist_id AS c_bp_m_pricelist_id,
    bp.numberemployees AS c_bp_numberemployees,
    bp.paymentrule AS c_bp_paymentrule,
    bp.paymentrulepo AS c_bp_paymentrulepo,
    bp.po_discountschema_id AS c_bp_po_discountschema_id,
    bp.po_paymentterm_id AS c_bp_po_paymentterm_id,
    bp.po_pricelist_id AS c_bp_po_pricelist_id,
    bp.poreference AS c_bp_poreference,
    bp.potentiallifetimevalue AS c_bp_potentiallifetimevalue,
    bp.rating AS c_bp_rating,
    bp.salesrep_id AS c_bp_salesrep_id,
    bp.salesvolume AS c_bp_salesvolume,
    bp.sendemail AS c_bp_sendemail,
    bp.shareofcustomer AS c_bp_shareofcustomer,
    bp.shelflifeminpct AS c_bp_shelflifeminpct,
    bp.so_creditlimit AS c_bp_so_creditlimit,
    bp.socreditstatus AS c_bp_socreditstatus,
    bp.so_creditused AS c_bp_so_creditused,
    bp.so_description AS c_bp_so_description,
    bp.totalopenbalance AS c_bp_totalopenbalance,
    bp.updated AS c_bp_updated,
    bp.updatedby AS c_bp_updatedby,
    bp.url AS c_bp_url,
    bp.isconsignmentpartner,
    bp.m_warehouse_id AS m_warehousetarget_id,
    bpg.ad_org_id AS c_greeting_ad_org_id,
    bpg.isactive AS c_greeting_isactive,
    bpg.isfirstnameonly,
    bpg.name AS c_greeting_name,
    bpl.ad_org_id AS c_bp_location_ad_org_id,
    bpl.c_bpartner_id AS c_bp_location_c_bpartner_id,
    bpl.created AS c_bp_location_created,
    bpl.createdby AS c_bp_location_createdby,
    bpl.c_salesregion_id,
    bpl.fax AS c_bp_location_fax,
    bpl.isactive AS c_bp_location_isactive,
    bpl.isbillto,
    bpl.isdn,
    bpl.ispayfrom,
    bpl.isremitto,
    bpl.isshipto,
    bpl.name AS c_bp_location_name,
    bpl.phone AS c_bp_location_phone,
    bpl.phone2 AS c_bp_location_phone2,
    bpl.updated AS c_bp_location_updated,
    bpl.updatedby AS c_bp_location_updatedby,
    l.address1,
    l.address2,
    l.address3,
    l.address4,
    l.ad_org_id AS c_location_ad_org_id,
    l.c_city_id,
    l.c_country_id,
    l.city,
    l.created AS c_location_created,
    l.createdby AS c_location_createdby,
    l.c_region_id,
    l.isactive AS c_location_isactive,
    l.regionname,
    l.updated AS c_location_updated,
    l.updatedby AS c_location_updatedby,
    bpc.ad_org_id AS ad_user_ad_org_id,
    bpc.ad_orgtrx_id AS ad_user_ad_ad_orgtrx_id,
    bpc.birthday AS ad_user_ad_birthday,
    bpc.c_bpartner_id AS ad_user_c_bpartner_id,
    bpc.c_bpartner_location_id AS ad_user_c_bpartner_location_id,
    bpc.c_greeting_id AS ad_user_c_greeting_id,
    bpc.comments AS ad_user_comments,
    bpc.created AS ad_user_created,
    bpc.createdby AS ad_user_createdby,
    bpc.description AS ad_user_description,
    bpc.email AS ad_user_email,
    bpc.fax AS ad_user_fax,
    bpc.isactive AS ad_user_isactive,
    bpc.lastcontact AS ad_user_lastcontact,
    bpc.lastresult AS ad_user_lastresult,
    bpc.phone2 AS ad_user_phone2,
    bpc.supervisor_id AS ad_user_supervisor_id,
    bpc.updated AS ad_user_updated,
    bpc.updatedby AS ad_user_updatedby,
    bpc.value AS ad_user_value,
    bpcg.ad_org_id AS c_user_greeting_ad_org_id,
    bpcg.isactive AS c_user_greeting_isactive,
    bpcg.isfirstnameonly AS c_user_greeting_isfnameonly,
    bpcg.name AS c_user_greeting_name,
    oi.ad_org_id AS ad_orginfo_ad_org_id,
    oi.ad_orgtype_id,
    oi.c_calendar_id,
    oi.created AS ad_orginfo_created,
    oi.createdby AS ad_orginfo_createdby,
    oi.dropship_warehouse_id,
    oi.duns AS ad_orginfo_duns,
    oi.email AS ad_orginfo_email,
    oi.fax AS ad_orginfo_fax,
    oi.isactive AS ad_orginfo_isactive,
    oi.m_warehouse_id AS ad_orginfo_m_warehouse_id,
    oi.parent_org_id,
    oi.phone AS ad_orginfo_phone,
    oi.phone2 AS ad_orginfo_phone2,
    oi.receiptfootermsg,
    oi.supervisor_id,
    oi.updated AS ad_orginfo_updated,
    oi.updatedby AS ad_orginfo_updatedby,
    wh.ad_org_id AS m_warehouse_ad_org_id,
    wh.description AS m_warehouse_description,
    wh.isactive AS m_warehouse__isactive,
    wh.isdisallownegativeinv,
    wh.isintransit AS m_warehouse_isintransit,
    wh.m_warehousesource_id,
    wh.name AS m_warehouse_name,
    wh.replenishmentclass,
    wh.separator,
    wh.value AS m_warehouse_value,
    wh.isconsignmentwarehouse,
    io.m_inout_id AS ftu_rv_inout_header_id
   FROM m_inout io
     JOIN c_doctype dt ON io.c_doctype_id = dt.c_doctype_id
     JOIN c_bpartner bp ON io.c_bpartner_id = bp.c_bpartner_id
     LEFT JOIN c_greeting bpg ON bp.c_greeting_id = bpg.c_greeting_id
     JOIN c_bpartner_location bpl ON io.c_bpartner_location_id = bpl.c_bpartner_location_id
     JOIN c_location l ON bpl.c_location_id = l.c_location_id
     LEFT JOIN ad_user bpc ON io.ad_user_id = bpc.ad_user_id
     LEFT JOIN c_greeting bpcg ON bpc.c_greeting_id = bpcg.c_greeting_id
     JOIN ad_orginfo oi ON io.ad_org_id = oi.ad_org_id
     JOIN ad_clientinfo ci ON io.ad_client_id = ci.ad_client_id
     JOIN m_warehouse wh ON io.m_warehouse_id = wh.m_warehouse_id;

ALTER TABLE adempiere.ftu_rv_inout_header
    OWNER TO adempiere;

-- View: adempiere.ftu_rv_inout_line

-- DROP VIEW adempiere.ftu_rv_inout_line;

CREATE OR REPLACE VIEW adempiere.ftu_rv_inout_line
 AS
 SELECT iol.ref_inoutline_id,
    iol.c_uom_id,
    iol.isinvoiced,
    iol.movementqty,
    iol.m_inout_id,
    iol.scrappedqty,
    iol.targetqty,
    iol.line,
    iol.qtyentered,
    iol.c_project_id,
    iol.confirmedqty,
    iol.user2_id,
    iol.user1_id,
    iol.c_projecttask_id,
    iol.m_rmaline_id,
    iol.reversalline_id,
    iol.isdescription,
    iol.description,
    iol.pickedqty,
    iol.m_inoutline_id,
    iol.updated,
    iol.isactive,
    iol.qtyoverreceipt,
    iol.ad_org_id,
    iol.ad_orgtrx_id,
    iol.c_projectphase_id,
    iol.c_activity_id,
    iol.c_campaign_id,
    iol.c_charge_id,
    iol.c_orderline_id,
    iol.m_attributesetinstance_id,
    iol.m_product_id,
    iol.created,
    iol.m_locator_id,
    iol.createdby,
    iol.updatedby,
    iol.ad_client_id,
    iol.qtyreceipt
   FROM m_inoutline iol
     JOIN m_inout io ON io.m_inout_id = iol.m_inout_id;

ALTER TABLE adempiere.ftu_rv_inout_line
    OWNER TO adempiere;

-- View: adempiere.ftu_rv_invoice_header

-- DROP VIEW adempiere.ftu_rv_invoice_header;

CREATE OR REPLACE VIEW adempiere.ftu_rv_invoice_header
 AS
 SELECT i.isfixedassetinvoice,
    i.isdiscountprinted,
    i.isapproved,
    i.totallines,
    i.ispaid,
    i.dateacct,
    i.c_project_id,
    i.dateordered,
    i.poreference,
    i.docstatus,
    i.istransferred,
    i.user2_id,
    i.grandtotal,
    i.isprinted,
    i.issotrx,
    i.sendemail,
    i.chargeamt,
    i.c_doctypetarget_id,
    i.ref_invoice_id,
    i.user1_id,
    i.processed,
    i.isselfservice,
    i.istaxincluded,
    i.isindispute,
    i.invoicecollectiontype,
    i.m_rma_id,
    i.c_dunninglevel_id,
    i.dunninggrace,
    i.c_order_id,
    i.c_paymentterm_id,
    i.description,
    i.dateinvoiced,
    i.documentno,
    i.updated,
    i.isactive,
    i.processedon,
    i.paymentrule,
    i.m_pricelist_id,
    i.ad_org_id,
    i.ad_orgtrx_id,
    i.ad_user_id,
    i.salesrep_id,
    i.c_bpartner_location_id,
    i.c_activity_id,
    i.c_bpartner_id,
    i.c_campaign_id,
    i.c_payment_id,
    i.c_cashline_id,
    i.c_cashplanline_id,
    i.c_charge_id,
    i.c_conversiontype_id,
    i.c_currency_id,
    i.created,
    i.reversal_id,
    i.dateprinted,
    i.ad_client_id,
    i.updatedby,
    i.createdby,
    i.c_doctype_id,
    i.c_invoice_id AS ftu_rv_invoice_header_id
   FROM c_invoice i;

ALTER TABLE adempiere.ftu_rv_invoice_header
    OWNER TO adempiere;


-- View: adempiere.ftu_rv_invoice_line

-- DROP VIEW adempiere.ftu_rv_invoice_line;

CREATE OR REPLACE VIEW adempiere.ftu_rv_invoice_line
 AS
 SELECT il.isfixedassetinvoice,
    il.a_createasset,
    il.c_invoice_id,
    il.pricelist,
    il.m_inoutline_id,
    il.priceactual,
    il.isprinted,
    il.c_tax_id,
    il.c_uom_id,
    il.line,
    il.qtyinvoiced,
    il.c_invoiceline_id,
    il.c_project_id,
    il.taxamt,
    il.linetotalamt,
    il.c_orderline_id,
    il.priceentered,
    il.qtyentered,
    il.pricelimit,
    il.s_resourceassignment_id,
    il.processed,
    il.user2_id,
    il.user1_id,
    il.a_asset_group_id,
    il.a_capvsexp,
    il.a_processed,
    il.m_attributesetinstance_id,
    il.rramt,
    il.c_projecttask_id,
    il.c_projectphase_id,
    il.m_rmaline_id,
    il.rrstartdate,
    il.description,
    il.linenetamt,
    il.m_product_id,
    il.c_invoiceline_uu,
    il.isdescription,
    il.updated,
    il.isactive,
    il.a_asset_id,
    il.ad_org_id,
    il.ad_orgtrx_id,
    il.c_1099box_id,
    il.c_activity_id,
    il.c_campaign_id,
    il.c_charge_id,
    il.ref_invoiceline_id,
    il.created,
    il.createdby,
    il.ad_client_id,
    il.updatedby
   FROM c_invoiceline il
     JOIN c_invoice i ON i.c_invoice_id = il.c_invoice_id;

ALTER TABLE adempiere.ftu_rv_invoice_line
    OWNER TO adempiere;

-- View: adempiere.ftu_rv_consignment_storage
-- DROP VIEW adempiere.ftu_rv_consignment_storage;

CREATE OR REPLACE VIEW adempiere.ftu_rv_consignment_storage AS 
SELECT ms.ad_client_id,
    ms.ad_org_id,
    max(ms.created) AS created,
    max(ms.createdby) as createdby,
    max(ms.updated) AS updated,
    max(ms.updatedby) as updatedby,
    ms.isactive,
    sum(ms.qtyonhand + COALESCE(mml.movementqty, 0::numeric)) AS actualqty,
    sum(ms.qtyonhand) AS qtyonhand,
    sum(COALESCE(mml.movementqty, 0::numeric)) AS movementqty,
    wh.m_warehouse_id,
    ml.m_locator_id, 
    prc.m_product_category_id,
    prc.name AS productcategoryname,
    wh.name AS warehousename,
    wh.value AS warehousevalue,
    ml.x,
    ml.y,
    ml.z,
    ml.value,
    pr.value AS productvalue,
    pr.sku,
    pr.name AS productname,
    ml.c_bpartner_id,
    ms.m_product_id 
   FROM (select ad_client_id,ad_org_id,isactive,m_locator_id,m_product_id,m_attributesetinstance_id,
    sum(qtyonhand) as qtyonhand, 
    max(created) AS created,
    max(createdby) as createdby,
    max(updated) AS updated,
    max(updatedby) as updatedby 
   	from m_storage 
   	group by ad_client_id,ad_org_id,isactive,m_locator_id,m_product_id,m_attributesetinstance_id) ms
     JOIN m_locator ml ON ml.m_locator_id = ms.m_locator_id
     JOIN m_warehouse wh ON wh.m_warehouse_id = ml.m_warehouse_id
     JOIN m_product pr ON pr.m_product_id = ms.m_product_id
     JOIN m_product_category prc ON prc.m_product_category_id = pr.m_product_category_id
     LEFT JOIN ( SELECT sum(mml_1.movementqty - mml_1.qtyinvoiced) AS movementqty,
            mml_1.m_locator_id,
            mml_1.m_product_id,
            mml_1.m_attributesetinstance_id
           FROM m_movementline mml_1
             JOIN m_movement mv ON mv.m_movement_id = mml_1.m_movement_id
             JOIN c_doctype dt ON dt.c_doctype_id = mv.c_doctype_id
        WHERE (mv.docstatus = ANY (ARRAY['CL'::bpchar, 'CO'::bpchar])) AND dt.isconsignmentdocument = 'Y'::bpchar 
          GROUP BY mml_1.m_locator_id, mml_1.m_product_id, mml_1.m_attributesetinstance_id ) mml ON mml.m_locator_id = ms.m_locator_id AND mml.m_product_id = ms.m_product_id AND mml.m_attributesetinstance_id = ms.m_attributesetinstance_id
  WHERE wh.isconsignmentwarehouse = 'Y'::bpchar 
  GROUP BY ms.ad_client_id, ms.ad_org_id, ms.isactive, wh.m_warehouse_id, ml.m_locator_id, prc.m_product_category_id, prc.name, wh.name, wh.value, ml.x, ml.y, ml.z, ml.value, pr.value, pr.sku, pr.name, ml.c_bpartner_id,ms.m_product_id;

ALTER TABLE adempiere.ftu_rv_consignment_storage
    OWNER TO adempiere;

-- View: adempiere.ftu_rv_invoices

-- DROP VIEW adempiere.ftu_rv_invoices;

CREATE OR REPLACE VIEW adempiere.ftu_rv_invoices
AS SELECT i.ad_client_id,
    i.ad_org_id,
    i.c_invoice_id,
    i.ispaid,
    i.dateacct,
    i.docstatus,
    i.grandtotal,
    i.c_doctypetarget_id,
    i.c_order_id,
    i.description,
    i.dateinvoiced,
    i.documentno,
    i.m_pricelist_id,
    i.c_bpartner_location_id,
    i.c_bpartner_id,
    i.c_conversiontype_id,
    i.c_currency_id,
    i.c_doctype_id,
    i.c_charge_id,
    il.m_inoutline_id,
    il.priceactual,
    il.c_uom_id,
    il.line,
    il.qtyinvoiced,
    il.c_invoiceline_id,
    il.taxamt,
    il.linetotalamt,
    il.c_orderline_id,
    il.priceentered,
    il.qtyentered,
    il.pricelimit,
    il.m_product_id,
    NULL::numeric(10,0) AS m_inout_id,
    ol.m_warehouse_id,
    NULL::numeric(10,0) AS m_locator_id,
    p.isconsignmentproduct,
    i.issotrx,
    i.salesrep_id,
    i.paymentrule,
    'INV'::character(3) AS type,
    COALESCE(( SELECT 'Y'::text AS text
           FROM c_order o
             JOIN c_doctype dt ON o.c_doctype_id = dt.c_doctype_id AND dt.isproformaorder = 'Y'::bpchar
             JOIN c_orderline ol_1 ON o.c_order_id = ol_1.c_order_id AND ol_1.c_invoiceline_id IS NOT NULL AND o.issotrx = 'N'::bpchar AND (o.docstatus = ANY (ARRAY['CO'::bpchar, 'CL'::bpchar, 'IP'::bpchar]))
             JOIN m_product prd ON ol_1.m_product_id = prd.m_product_id AND prd.isconsignmentproduct = 'Y'::bpchar
          WHERE ol_1.c_invoiceline_id = il.c_invoiceline_id), 'N'::text) AS isgenerated,
    COALESCE(( SELECT pl.m_pricelist_id
           FROM m_pricelist pl
             JOIN m_pricelist_version plv ON pl.m_pricelist_id = plv.m_pricelist_id
             JOIN m_productprice pp ON plv.m_pricelist_version_id = pp.m_pricelist_version_id
          WHERE pl.issopricelist = 'N'::bpchar AND i.ad_org_id = pl.ad_org_id AND il.m_product_id = pp.m_product_id AND plv.validfrom <= i.dateinvoiced
          ORDER BY plv.validfrom DESC, plv.created
         LIMIT 1), i.m_pricelist_id) AS po_pricelist_id,
    COALESCE(( SELECT pp.pricestd
           FROM m_pricelist pl
             JOIN m_pricelist_version plv ON pl.m_pricelist_id = plv.m_pricelist_id
             JOIN m_productprice pp ON plv.m_pricelist_version_id = pp.m_pricelist_version_id
          WHERE pl.issopricelist = 'N'::bpchar AND i.ad_org_id = pl.ad_org_id AND il.m_product_id = pp.m_product_id AND plv.validfrom <= i.dateinvoiced
          ORDER BY plv.validfrom DESC, plv.created
         LIMIT 1), 0::numeric) AS pricestd,
    NULL::numeric(10,0) AS m_inventory_id,
    NULL::numeric(10,0) AS m_inventoryline_id
   FROM c_invoice i
     JOIN c_invoiceline il ON il.c_invoice_id = i.c_invoice_id
     JOIN c_orderline ol ON ol.c_orderline_id = il.c_orderline_id
     JOIN m_product p ON p.m_product_id = il.m_product_id AND p.isconsignmentproduct = 'Y'::bpchar
  WHERE i.docstatus = 'CO'::bpchar AND i.issotrx = 'Y'::bpchar
UNION ALL
 SELECT i.ad_client_id,
    i.ad_org_id,
    NULL::numeric(10,0) AS c_invoice_id,
    'N'::character(1) AS ispaid,
    i.movementdate AS dateacct,
    i.docstatus,
    i.approvalamt AS grandtotal,
    i.c_doctype_id AS c_doctypetarget_id,
    io.c_order_id,
    i.description,
    i.movementdate AS dateinvoiced,
    i.documentno,
    o.m_pricelist_id,
    o.c_bpartner_location_id,
    o.c_bpartner_id,
    o.c_conversiontype_id,
    o.c_currency_id,
    i.c_doctype_id,
    il.c_charge_id,
    il.m_inoutline_id,
    NULL::numeric(10,0) AS priceactual,
    NULL::numeric(10,0) AS c_uom_id,
    il.line,
    il.qtyinternaluse AS qtyinvoiced,
    NULL::numeric(10,0) AS c_invoiceline_id,
    NULL::numeric(10,0) AS taxamt,
    NULL::numeric(10,0) AS linetotalamt,
    NULL::numeric(10,0) AS c_orderline_id,
    NULL::numeric(10,0) AS priceentered,
    NULL::numeric(10,0) AS qtyentered,
    NULL::numeric(10,0) AS pricelimit,
    il.m_product_id,
    i.m_inout_id,
    i.m_warehouse_id,
    NULL::numeric(10,0) AS m_locator_id,
    p.isconsignmentproduct,
    io.issotrx,
    o.salesrep_id,
    o.paymentrule,
    'IUI'::character(3) AS type,
    COALESCE(( SELECT 'Y'::text AS text
           FROM c_order o_1
             JOIN c_doctype dt_1 ON o_1.c_doctype_id = dt_1.c_doctype_id AND dt_1.isproformaorder = 'Y'::bpchar
             JOIN c_orderline ol ON o_1.c_order_id = ol.c_order_id AND ol.m_inventoryline_id IS NOT NULL AND o_1.issotrx = 'N'::bpchar AND (o_1.docstatus = ANY (ARRAY['CO'::bpchar, 'CL'::bpchar, 'IP'::bpchar]))
             JOIN m_product prd ON ol.m_product_id = prd.m_product_id AND prd.isconsignmentproduct = 'Y'::bpchar
          WHERE ol.m_inventoryline_id = il.m_inventoryline_id), 'N'::text) AS isgenerated,
    COALESCE(( SELECT pl.m_pricelist_id
           FROM m_pricelist pl
             JOIN m_pricelist_version plv ON pl.m_pricelist_id = plv.m_pricelist_id
             JOIN m_productprice pp ON plv.m_pricelist_version_id = pp.m_pricelist_version_id
          WHERE pl.issopricelist = 'N'::bpchar AND i.ad_org_id = pl.ad_org_id AND il.m_product_id = pp.m_product_id AND plv.validfrom <= i.movementdate
          ORDER BY plv.validfrom DESC, plv.created
         LIMIT 1), o.m_pricelist_id) AS po_pricelist_id,
    COALESCE(( SELECT pp.pricestd
           FROM m_pricelist pl
             JOIN m_pricelist_version plv ON pl.m_pricelist_id = plv.m_pricelist_id
             JOIN m_productprice pp ON plv.m_pricelist_version_id = pp.m_pricelist_version_id
          WHERE pl.issopricelist = 'N'::bpchar AND i.ad_org_id = pl.ad_org_id AND il.m_product_id = pp.m_product_id AND plv.validfrom <= i.movementdate
          ORDER BY plv.validfrom DESC, plv.created
         LIMIT 1), 0::numeric) AS pricestd,
    i.m_inventory_id,
    il.m_inventoryline_id
   FROM m_inventory i
     JOIN m_inventoryline il ON il.m_inventory_id = i.m_inventory_id
     JOIN m_inout io ON io.m_inout_id = i.m_inout_id
     JOIN c_order o ON o.c_order_id = io.c_order_id
     JOIN c_doctype dt ON dt.c_doctype_id = io.c_doctype_id
     JOIN m_product p ON p.m_product_id = il.m_product_id
  WHERE (i.docstatus = ANY (ARRAY['CO'::bpchar, 'CL'::bpchar])) AND dt.isconsignmentdocument = 'Y'::bpchar AND io.issotrx = 'N'::bpchar;

ALTER TABLE adempiere.ftu_rv_invoices
    OWNER TO adempiere;

GRANT ALL ON TABLE adempiere.ftu_rv_invoices TO adempiere;

-- View: adempiere.ftu_rv_consignmentmovement

-- DROP VIEW adempiere.ftu_rv_consignmentmovement;

CREATE OR REPLACE VIEW adempiere.ftu_rv_consignmentmovement
AS SELECT ml.m_movementline_id,
    ml.movementqty,
    ml.m_product_id,
    m.movementdate,
    m.m_movement_id,
    l.c_bpartner_id,
    ml.m_inoutline_id,
    COALESCE(ml.qtyinvoiced, 0::numeric) AS qtyinvoiced,
    ml.created,
    ml.movementqty - COALESCE(ml.qtyinvoiced, 0::numeric) AS qty
   FROM m_movement m
     JOIN c_doctype dt ON dt.c_doctype_id = m.c_doctype_id
     JOIN m_movementline ml ON m.m_movement_id = ml.m_movement_id
     JOIN m_locator l ON l.m_locator_id = ml.m_locator_id
  WHERE m.docstatus = 'CO'::bpchar AND dt.isconsignmentdocument = 'Y'::bpchar
  GROUP BY ml.m_product_id, l.c_bpartner_id, ml.m_movementline_id, m.m_movement_id;

ALTER TABLE adempiere.ftu_rv_consignmentmovement
    OWNER TO adempiere;

CREATE OR REPLACE VIEW adempiere.ftu_rv_relatedmovement
AS SELECT iol.movementqty,
    iol.m_inout_id,
    io.description AS inoutdescription,
    io.documentno,
    uom.c_uom_id,
    uom.name AS uomname,
    uom.x12de355,
    iol.description,
    loc.m_locator_id,
    loc.x,
    loc.y,
    loc.z,
    iol.m_product_id,
    p.value AS productvalue,
    p.name AS productname,
    iol.m_inoutline_id,
    iol.movementqty - COALESCE(sum(mml.movementqty), 0::numeric) AS availableqty,
    wh.name AS warehousename,
    wh.value AS warehousevalue
   FROM m_inoutline iol
     JOIN m_inout io ON io.m_inout_id = iol.m_inout_id
     JOIN c_uom uom ON uom.c_uom_id = iol.c_uom_id
     JOIN m_locator loc ON loc.m_locator_id = iol.m_locator_id
     JOIN m_product p ON iol.m_product_id = p.m_product_id
     JOIN c_doctype dt ON dt.c_doctype_id = io.c_doctype_id
     JOIN m_warehouse wh ON wh.m_warehouse_id = loc.m_warehouse_id
     LEFT JOIN ( SELECT ml.movementqty,
            ml.m_inoutline_id
           FROM m_movementline ml
             JOIN m_movement m ON m.m_movement_id = ml.m_movement_id
             JOIN c_doctype dtm ON dtm.c_doctype_id = m.c_doctype_id
          WHERE (m.docstatus = ANY (ARRAY['CL'::bpchar, 'CO'::bpchar])) AND dtm.isconsignmentdocument = 'Y'::bpchar) mml ON mml.m_inoutline_id = iol.m_inoutline_id
  WHERE iol.isconfirmed = 'Y'::bpchar AND iol.movementqty > 0::numeric AND dt.isconsignmentdocument = 'Y'::bpchar AND io.movementtype = 'V+'::bpchar AND dt.isconsignmentdocument = 'Y'::bpchar
  GROUP BY iol.m_inoutline_id, io.m_inout_id, uom.c_uom_id, loc.m_locator_id, p.m_product_id, wh.m_warehouse_id;

-- Permissions

ALTER TABLE adempiere.ftu_rv_relatedmovement OWNER TO adempiere;
GRANT ALL ON TABLE adempiere.ftu_rv_relatedmovement TO adempiere;